config/routes.rb
Rails.application.routes.draw do
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :impression, presence: true
  # validates :star, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }
  has_one_attached :cover
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: "保存しました"
    else
      flash.now[:alert] = "保存できませんでした"
      render :new
    end
  end

  def index
    @books = Book.all
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "登録を削除しました"
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to books_path, notice: "編集しました"
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :impression, :star, :rating, :cover)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>登録の編集</h1>
<%= link_to "一覧", books_path %>

<%= form_with model: @book, html: {class: "edit-form"} do |f| %>
    <div>
    <%= f.label :title, 'タイトルを入力' %><br>
    <%= f.text_field :title, class: "input-field" %>
    </div>

    <div>
        <%= f.label :author, 'author' %><br>
        <%= f.text_field :author, class: "input-field" %>
    </div>

    <div>
        <%= f.label :impression, '感想' %><br>
        <%= f.text_area :impression, class: "textarea-field" %>
    </div>

    <div>
        <%= f.label :rating, '評価' %>
        <%= f.number_field :rating, class: "input-field" %>
    </div>

    <%= f.submit "編集する", class: "submit" %>
<% end %>

app/views/books/index.html.erb
<div class="top"><h1>読んだ本一覧❤<h1></div>
<div class="align-container">
    <%= link_to '新規登録', new_book_path, class: "add-book-button" %><br>
</div>


<div class="books-container">
  <% @books.each do |book| %>
    <div class="book-card">
        <%= link_to book.title, book_path(book), class: "book-action-link" %>
        <p>評価:
            <%= (book.rating || 0).times do %>
                ★
            <% end %>
        </p>
    </div>

<div class="book-actions">
    <%= button_to "削除", book_path(book), method: :delete, data: { confirm: "本当に削除しますか？" } %>
    <%= link_to "編集", edit_book_path(book), class: "book-action-link" %>
</div>
<% end %>

</div>

app/views/books/new.html.erb
<h1>本を登録する</h1>
<div class="new-action-link-wrapper">
    <%= link_to '一覧', books_path, class: 'new-action-link'%>
</div>

<h2><%= @book.errors.count %>件のエラーがあります。</h2>
<ul>
    <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
</ul>

<%= form_with model: @book, html: {class: "new-form"}, local: true do |f| %>
    <div>
    <%= f.label :title, 'タイトルを入力' %><br>
    <%= f.text_field :title, class: 'new-input-field' %>
    </div>

    <div>
        <%= f.label :author, 'author' %><br>
        <%= f.text_field :author, class: 'new-input-field' %>
    </div>

    <div>
        <%= f.label :impression, '感想' %><br>
        <%= f.text_area :impression, class: 'impression-field' %>
    </div>

    <div class="rating">
        <% 5.times do |i|%>
            <span class="star" data-value="<%= i + 1 %>">&#9733;</span>
        <% end %>
    </div>
    <%= f.hidden_field :rating, id: "rating-value" %>

    <div class="form-group">
        <%= f.label :cover, "表示画像" %><br>
        <%= f.file_field :cover, accept: "image/*" %>
    </div>

    <button type="submit" class="btn-flat">保存する</button>
<% end %>

app/views/books/show.html.erb
<h1>詳細ページ</h1>
<%= link_to '一覧', books_path, class: 'big-action-button' %>

<% if @book.cover.attached? %>
    <div class="book-cover-wrapper">
        <%= image_tag @book.cover, class: "book-cover" %>
    </div>
<% end %>

<div class='show-container'>
    <h2><%= @book.title %></h2>
    <%= @book.rating.times do %>
    ★
<% end %>
<p><%= @book.author %></p>
<p><%= @book.impression %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Book App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <% if flash[:notice] %>
      <p class="flash flash-notice"><%= flash[:notice] %></p>
    <% end %>

    <% if flash[:alert] %>
      <p class="flash flash-alert"><%= flash[:alert] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>